export const FETCHING_CATEGORIES = 'FETCHING_CATEGORIES'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR'

export const FETCHING_CATEGORY_DISHES = 'FETCHING_CATEGORY_DISHES'
export const FETCH_CATEGORY_DISHES_SUCCESS = 'FETCH_CATEGORY_DISHES_SUCCESS'
export const FETCH_CATEGORY_DISHES_ERROR = 'FETCH_CATEGORY_DISHES_ERROR'
